# Generated by Django 4.2.2 on 2023-06-27 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProducto', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPedido', models.PositiveIntegerField()),
                ('fechaPedido', models.DateField()),
                ('estadoPedido', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ruta', 'En ruta'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('pagoPedido', models.BooleanField(default=False)),
                ('nombreCliente', models.CharField(max_length=100)),
                ('emailCliente', models.EmailField(max_length=100)),
                ('direccionCliente', models.CharField(max_length=100)),
                ('ciudadCliente', models.CharField(max_length=100)),
                ('reglaEnvio', models.CharField(choices=[('domicilio', 'Domicilio'), ('punto de Venta', 'Punto de Venta')], max_length=20)),
                ('observaciones', models.CharField(max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionClientes.producto')),
            ],
        ),
    ]
