# Generated by Django 4.2.2 on 2023-06-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionClientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=100)),
                ('emailCliente', models.EmailField(max_length=100)),
                ('direccionCliente', models.CharField(max_length=100)),
                ('ciudadCliente', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='ciudadCliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='direccionCliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='emailCliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nombreCliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='producto',
        ),
    ]
