# Generated by Django 4.2.2 on 2023-06-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionClientes', '0005_alter_producto_descripcion_alter_producto_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=100)),
                ('emailUsuario', models.EmailField(max_length=100)),
                ('emailPassword', models.CharField(max_length=100)),
            ],
        ),
    ]
